apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -v convert -f .\docker-compose.yaml -o deployment
    kompose.service.expose: tagawsome.com
    kompose.service.expose.ingress-class-name: nginx
    kompose.service.expose.tls-secret: atay-secret
    kompose.service.type: LoadBalancer
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: app-tcp
  name: app-tcp
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    io.kompose.service: app
  type: LoadBalancer
status:
  loadBalancer: {}
